apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: default
images:
  - name: lp-helloworld-app
    newName: docker.io/stephenwilliams/lp-helloworld-app
    newTag: 544a51068a3eaca714d1bbb05d86550f382a127e
